services:

  rsscloud:
    build: .
    command: node --use_strict app.js
    environment:
      DOMAIN: rsscloud
      PORT: 5337
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      ENABLE_TEST_API: "true"
    expose:
      - 5337

  rsscloud-tests:
    build: .
    command: dockerize -wait http://rsscloud:5337 -timeout 10s bash -c "pnpm exec mocha"
    environment:
      APP_URL: http://rsscloud:5337
      MOCK_SERVER_DOMAIN: rsscloud-tests
      MOCK_SERVER_PORT: 8002
      SECURE_MOCK_SERVER_PORT: 8003
    volumes:
      - ./xunit:/app/xunit
    expose:
      - 8002
      - 8003
    depends_on:
      - rsscloud

